// <auto-generated />
namespace PayTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatingcustomerkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatingcustomerkey));
        
        string IMigrationMetadata.Id
        {
            get { return "202202250420562_updating customer key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
