// <auto-generated />
namespace JobTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedsoldamountandearningsintoedit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedsoldamountandearningsintoedit));
        
        string IMigrationMetadata.Id
        {
            get { return "202202170007277_added sold amount and earnings into edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
