// <auto-generated />
namespace PayTracker.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatedcreatemethods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedcreatemethods));
        
        string IMigrationMetadata.Id
        {
            get { return "202202140412369_updated create methods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
